version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "8888:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=companyDB
      - DB_USER=user
      - DB_PASS=user
    depends_on:
      - db
    volumes:
      - .:/app
    restart: on-failure
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: companyDB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgres
    restart: on-failure

