# Generated by Django 4.2.1 on 2023-05-04 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(auto_now=True)),
                ('first_course', models.CharField(blank=True, max_length=100)),
                ('main_course', models.CharField(max_length=100)),
                ('dessert', models.CharField(blank=True, max_length=100)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='restaurant.restaurantmodel')),
            ],
            options={
                'db_table': 'menus',
            },
        ),
    ]
